name: LinkGrabber

on:
  schedule:
    - cron: '0 */3 * * *'   # corre cada 3 horas
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  runCode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # versión nueva, compatible con Node.js 24

      - name: Grab Link
        run: |
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add youtube.m3u8 epg.xml
          git commit -m "Update playlist" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
